### ISSUE TITLE
Protein coordinates --> genomic coordinates

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/cool-seq-tool#120]
@jarbesfeld needs a new endpoint for going from protein coordinates to genomic coordinates. Below are the requirements:

- Input parameters: `p_ac` (NP accession), `start_p_pos`, `end_p_pos`, `tx_ac` (NM accession), `residue_mode`, `do_liftover`
  - `tx_ac` tells us which transcript to align to 
  - Default `residue_mode` will be `inter-residue`
  - Default `do_liftover` will be `True`. When set to `True` will return GRCh38. Else, return `GRCh37`
-  Output will look like:
    ```json
    {"genomic_ac": "NC_00007.14", "start_g_pos": 177777, "end_g_pos": 177778, "transcript": "NM_00004.3", "residue_mode": "inter-residue"}
    ```

**Comment by ahwagner** [comment]
Should we instead have a "target genome assembly" instead of "do liftover", with the target genome set to GRCh38 default?

**Comment by korikuzma** [comment]
> Should we instead have a "target genome assembly" instead of "do liftover", with the target genome set to GRCh38 default?

I can rename the param to `target_genome_assembly`

**Comment by korikuzma** [comment]
I don't think it's necessary to include `p_ac` as an input parameter. We multiply the `p_start_pos` and `p_end_pos` to get the `c_pos`. The aligned transcript is already given by `tx_ac`. 

Also, changing the output to look like:
```json
{
  "alt_ac": "NC_000007.13",
  "start_g_pos": 140453138,
  "end_g_pos": 140453136,
  "residue_mode": "inter-residue"
}
```

I don't think it's necessary to include `tx_ac` in the output since it's provided as input.

**Comment by ahwagner** [comment]
Good call-out, @korikuzma. I think we are describing two methods here.
1. Protein -> Genomic
2. Transcript -> Genomic

Building Transcript-> Genomic first makes sense, but we will want a protein -> transcript method as well, to go from aa coordinates to transcript coordinates. The overall method described here should be:

```pseudocode
Protein to Genomic Coordinates:
# Given a protein accession and position, return associated genomic coordinates aligned to the codon for the aa sequence
  1. Protein to Transcript (p_ac, p_start, p_end) # returns transcript accession and coordinates
  2. Transcript to Genomic (tx_ac, t_start, t_end, target_genome) # returns transcript coordinates mapped to target genome

**Comment by korikuzma** [comment]
@ahwagner I've been talking with Jeremy about this. He said he is able to give me the aligned transcript he used, so we won't need the associated protein accession when going from p --> c. We just multiple the protein pos by 3 to get the associated cDNA position. So this allows us to go from p --> c -- > g. 

I think we could create a separate ticket for general uses, when `tx_ac` is not available. In that case, we'd either use our transcript priority or return all aligned genomic representations for each transcript associated to the protein accession.

**Comment by korikuzma** [comment]
@jarbesfeld @ahwagner he is an example of what I currently have. Let me know if I need to make any changes. 

curl -X 'GET' \
  'http://127.0.0.1:8000/cool_seq_tool/p_coords_to_g_coords?p_ac=NP_004324.2&p_start_pos=599&p_end_pos=600&tx_ac=NM_004333.6&residue_mode=inter-residue&target_genome_assembly=GRCh37' \
  -H 'accept: application/json'

Output: 
```json
{
  "genomic_data": {
    "alt_ac": "NC_000007.13",
    "start_pos": 140453135,
    "end_pos": 140453136,
    "residue_mode": "inter-residue"
  },
  "warnings": [],
  "service_meta": {
    "name": "cool_seq_tool",
    "version": "0.1.6",
    "response_datetime": "2023-02-27T10:38:41.568594",
    "url": "https://github.com/GenomicMedLab/cool-seq-tool"
  }
}
```

**Comment by korikuzma** [comment]
@ahwagner @jarbesfeld Below are the tasks.

- [ ] Create these two endpoints and expose on Variation Normalizer (will make a separate issue in Variation Normalizer):
  - [ ] Protein --> Genomic
    - Input: `p_ac`, `start_pos`, `end_pos`, `residue_mode`, `target_genome_assembly`
    - Output: `alt_ac`, `start_pos`, `end_pos` (inter-residue)
  - [ ] Transcript --> Genomic
    - Input: `tx_ac`, `start_pos`, `end_pos`, `residue_mode`, `target_genome_assembly`
    - Output: `alt_ac`, `start_pos`, `end_pos` (inter-residue)
