### ISSUE TITLE
Decrease initial app startup time 

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/cool-seq-tool#140]
Similar to [this](https://app.zenhub.com/workspaces/wagner-lab-612eb99450b02c0012afa744/issues/gh/cancervariants/variation-normalization/369) issue in variation-normalizer

**Comment by korikuzma** [comment]
We mainly need this for variation-normalizer to serverless work.

**Comment by jsstevenson** [comment]
good enough
