### ISSUE TITLE
Investigate Pandas-less data processing 

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#178]
Pandas is a pretty large package, which hits us at startup for about half a second and also makes dependency upkeep more complicated. It'd be cool if we could see about whether lighter alternatives can achieve the same kind of lookup speed.

We're using Pandas for a few things:

1) easy lookups into the MANE transcript summary file
2) filtering (e.g. dropping duplicate rows) and sorting transcript results for genes

I think for 2), we might be able to accomplish some of this within the SQL engine. 1) might be thornier but the MANE summary file appears to be a little less than 20k rows, which might be small enough that we could just read into an in-memory dict.

I'm not super confident doing the above would achieve performance or startup gains but it's probably a place to look as we begin to try to improve in those areas.

**Comment by korikuzma** [comment]
The MANE data doesn’t seem to update that often. We could do some data transformations we need and store it. We could probably do this for the other files (transcript mappings and LRG Ref Seq) as well…

**Comment by korikuzma** [comment]
@jsstevenson https://pypi.org/project/polars/ ?

**Comment by jsstevenson** [comment]
I think Polars would be better -- probably would make things lighter at startup, at least. In the long term I still think it'd be better to see if we can just do this stuff with native Python, since it doesn't seem like it should be that complicated (?) but if we can quickly swap Pandas for Polars and see better startup times, that's a quick win.

**Comment by jsstevenson** [comment]
Fine to close for now
