### ISSUE TITLE
Rearrange resource classes architecture

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#192]
Was thinking about this while writing documentation. I think there are three separate kinds of "services"/tasks that `cool-seq-tool` provides, which could be made into three different kinds of modules:

1. Data sources. Provides basic acquisition/setup in Python for the various resources that we use. Some resources probably already do this themselves, eg SeqRepo and the Gene Normalizer, and maybe we could avoid redefining them here.
2. Data "consumers"/"retrievers" (name forthcoming?). These would be wrappers around the data sources that provide common and useful operations that they don't, themselves, provide. For SeqRepo, `chromosome_to_ac`/`ac_to_chromosome` methods are good examples of this. I think we also have frequent needs to fetch the HGNC symbol specifically associated with a normalized gene. 
3. Data "integrators". This would be classes that use more than one "retriever" to perform operations that integrate multiple kinds of data. The `MANETranscript` class is a good example of this. The root `cool-seq-tool` class, which we've sort of just used to house various operations needed for fusions, could probably be moved over to this other thing (although the FASTA method should probably just live in the SeqRepo accessor.

We could maybe retain a core `cool-seq-tool` class that can create all of these for ease of use. But I think something like the above is a little easier to explain and to diagram, and helps ensure that people don't accidentally try to use more resources than they need. Otherwise, I don't really think this would require writing much new code, it would just entail moving stuff around/splitting things out into separate modules and packages (which of course would temporarily break downstream compatibility).

***I think breaking this out could also help with Dockerization/portability. If data sources provide the interface to a given resource, they can also be rewritten as proxies to connect to Docker images or remote endpoints.

**Comment by jsstevenson** [comment]
![image](https://github.com/GenomicMedLab/cool-seq-tool/assets/12942397/2ac21cdc-6d30-4c4e-bce3-b42168d43db5)

^ this was my original attempt to diagram out how this could work

**Comment by korikuzma** [comment]
I am removing Gene Normalizer class in #189

**Comment by korikuzma** [comment]
I'm going to make a separate issue in vrs-python for adding the SeqRepoAccess methods that are commonly used

**Comment by korikuzma** [comment]
Going to address #158 here

**Comment by korikuzma** [comment]
@jsstevenson Do you think we need the data prefix for these?

**Comment by jsstevenson** [comment]
@korikuzma data prefix not necessary, mappers == good name
