### ISSUE TITLE
Remove `get_mapped_mane_data` 

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/cool-seq-tool#194]
Will do this once VRS 2.0-alpha supports Chromosome Locations

**Comment by korikuzma** [comment]
@jsstevenson I've checked fusor, fusion-curation, variation-normalizer, dcd_mapping and this method does not seem to be used anywhere. I think I'm going to completely remove if I'm not missing anything?

**Comment by jsstevenson** [comment]
Yeah you'd be the only person using it I imagine

**Comment by korikuzma** [comment]
> Yeah you'd be the only person using it I imagine

say less. deleting

**Comment by korikuzma** [comment]
Done in #196
