### ISSUE TITLE
Consider dropping API endpoints

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#208]
Two questions:

1) Do we want to host these endpoints independently?

2) Would work here be reusable elsewhere? Would it be better to implement here rather than in a more tailored way elsewhere?

If the answer is no to both, then we can consider dropping them.

**Comment by korikuzma** [comment]
We can remove and then close #198

**Comment by korikuzma** [comment]
@jarbesfeld can you comment on this? Are we good to remove these?

**Comment by jarbesfeld** [comment]
@korikuzma I think these can be removed
