### ISSUE TITLE
Liftover file params in `UTADatabase.__init__()` not usable

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#227]
In keeping with how we have written the other classes, `UTADatabase` accepts a couple of `__init__` args relating to specific locations for input files. However, users aren't supposed to call `__init__` directly -- they're supposed to call the `create()` method, but it doesn't have params for the chainfile inputs. We should probably add them as args to `create()`.

**Comment by korikuzma** [comment]
@jsstevenson Liftover is going to be moved in a separate module as a separate class in #158
