### ISSUE TITLE
Update type annotation in `MANETranscript.g_to_mane_c`

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#230]
The type for `end_pos` is `int`, but several of the tests pass `None` as a value, so I think it probably just needs to be `Optional[int]` (this is very nitpicky). Might also be able to give it `None` by default?

**Comment by korikuzma** [comment]
We can close this. In #176 I am making start/end both required (`issue-176-pos` branch, still wip)
