### ISSUE TITLE
Return exon that is adjacent to a genomic breakpoint

### ISSUE THREAD

**Issue by jarbesfeld** [GenomicMedLab/cool-seq-tool#266]
This method will be used in FUSOR when a genomic breakpoint does not occur within an exon, and the closest exon to the breakpoint is needed to create a `TranscriptSegmentElement`.

**Comment by ahwagner** [comment]
Is "closest" the right metric here? Perhaps it should be "first adjacent", and be orientation specific? Consider the following:
![Gene Fusion Information Model - Page 4](https://github.com/GenomicMedLab/cool-seq-tool/assets/811065/03b66b79-cb67-4280-a139-6a4354c6e212)

Here is a rearrangement (in + strand orientation) that results in a Gene A::Gene B fusion, with Gene A in a position that is 5' of Gene B. The red break occurs _closest_ to Gene A Exon 2, but the _first 5' adjacent_ is Gene A Exon 1. Similarly, the orange break is closest to Gene B Exon 4, but the first 3' adjacent is Gene B Exon 5.

**Comment by jarbesfeld** [comment]
@ahwagner Do you have a similar diagram for the - strand orientation?
