### ISSUE TITLE
Clean up UTA setup instructions

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#283]
Doing this on a new machine and noticed a few small things:

https://coolseqtool.readthedocs.io/latest/install.html#set-up-uta

1) zsh doesn't support comments by default, so the `# newest version` line should be taken out
2) some mention of the expected postgres post (5433) should be made *before* the code block, as this is not the typical PG default port, and the part of the command with the port is probably not visible on most screens until you scroll. maybe make it a separately declared env var so that it's more explicit.

**Comment by korikuzma** [comment]
@jsstevenson can we close? Both points have been addressed
