### ISSUE TITLE
Don't download resource files on import

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#284]
The externally-acquired data files are currently downloaded when you import Cool-Seq-Tool. This is sort of weird behavior by itself but also can cause confusing errors if e.g. the FTP connection decides to be slow. It'd be better to acquire these resources lazily or at least when the consuming classes are created.

**Comment by jsstevenson** [comment]
It also means that you can't import anything unless you have a working internet connection, which isn't ideal

**Comment by korikuzma** [comment]
> It also means that you can't import anything unless you have a working internet connection, which isn't ideal - there should be a way to create classes without acquiring new data if existing data is available

Agree, not ideal. I had thought we allowed local data to be used if env vars were set, but it's been a while since I look at cool seq tool

**Comment by jsstevenson** [comment]
Oh @korikuzma that's probably true -- I'll double check that this is made explicit in the docs
