### ISSUE TITLE
Counterintuitive/wrong? offset from genomic to transcript mapping

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#332]
### Describe the bug

Mapping the beginning genomic coordinate of exon 1 on ELN on a GRCh37 accession produces a genomic data description with an exon offset of -97. This is counterintuitive (wrong even?) -- I would expect it to map to the beginning of exon 1 on a GRCh38 accession, ie it should map to exon 1 with offset 0.

### Steps to reproduce

```python
from cool_seq_tool.app import CoolSeqTool
import asyncio

from cool_seq_tool.schemas import Strand

async def do_thing():
    cst = CoolSeqTool()
    result = await cst.ex_g_coords_mapper.genomic_to_transcript_exon_coordinates(
        alt_ac="NC_000007.13",
        start=73442503,  # this is the start of exon 1 on this gene/ac -- see https://www.ncbi.nlm.nih.gov/projects/sviewer/?id=NC_000007.13&tkey=KAJKLycgLCUiKyYpDRw5JR9XRUpiWVlhdUpVf1zLfSA0VyXsgas3w_8zqs-w-8PLsK8&assm_context=GCF_000001405.25&app_context=gene&v=73442488:73442615&c=null&select=null&slim=0
        strand=Strand.POSITIVE,
        gene="ELN",
    )
    print(result.genomic_data.exon_start_offset)

asyncio.run(do_thing())
# -97
``` 

### Expected behavior

Should be an exon offset of ~0

### Current behavior

Gives an offset of `-97`

### Possible reason(s)

`_set_exon_offset` looks fishy imho

### Branch, commit, and/or version

[efa56e1](https://github.com/GenomicMedLab/cool-seq-tool/commit/efa56e12690dc348fffe98dfe0fc058076ad36e7)

### Environment details

mac

### Additional details

I have yet to find another example of a gene on GRCh37 that maps to a transcript at all, so this might be specific to this gene

### Contribution

Yes, I can create a PR for this fix.

**Comment by korikuzma** [comment]
@jarbesfeld says this expected output from #352 is correct:

```json
{
  "gene": "ELN",
  "genomic_ac": "NC_000007.14",
  "tx_ac": "NM_000501.4",
  "seg_start": {
    "exon_ord": 0,
    "offset": 1,
    "genomic_location": {
      "type": "SequenceLocation",
      "sequenceReference": {
        "type": "SequenceReference",
        "refgetAccession": "SQ.F-LrLMe1SRpfUZHkQmvkVKFEGaoDeHul"
      },
      "start": 74028173
    }
  }
}
```

**Comment by korikuzma** [comment]
This was completed in #352
