### ISSUE TITLE
Wrong location in `ExonGenomicCoordsMapper.transcript_to_genomic_coordinates`

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#345]
### Describe the bug

The genomic location for an exon in the following lookup appears to be incorrect.

### Steps to reproduce

run this

```python
from cool_seq_tool.app import CoolSeqTool
import asyncio

async def do_thing():
    egc = CoolSeqTool().ex_g_coords_mapper
    result = await egc.transcript_to_genomic_coordinates(
        "NM_002529.4",  # latest NTRK1 transcript ac
        "NTRK1",
        exon_start=1
    )
    print(result.genomic_data.start)  # 156861145
    print(result.genomic_data.strand)  # 1 (ie positive)

asyncio.run(do_thing())
```

### Expected behavior

I think this is the *ending* coordinate of exon 1, not the *starting* coordinate.

1) see this screenshot from the ncbi genome data viewer
<img width="880" alt="Screenshot 2024-08-02 at 4 11 00 PM" src="https://github.com/user-attachments/assets/d629a191-0594-482c-a62a-cb2bd8162377">

2) take a look at the result of this UTA query:

```sql
SELECT * FROM tx_exon_aln_v WHERE tx_ac = 'NM_002529.4' AND alt_aln_method='splign' AND alt_ac = 'NC_000001.11' AND ord = 0;
```

Also, I don't think this would matter, but this transcript aligns to the positive strand of chr1 (am I saying that right?) so there shouldn't be any weird "end is start and start is end" issues here

### Current behavior

As noted above, the returned starting location is `156861145`

### Branch, commit, and/or version

The 0.5.1 release (it's what we have pinned for fusions) but I don't think it would be different on 0.6.0

### Environment details

mac

### Contribution

Yes, I can create a PR for this fix.

**Comment by korikuzma** [comment]
@jsstevenson I am resolving this in #224 . This was when we didn't know when to use start or end for the exon. @jarbesfeld has helped clear things up in the past few weeks!

**Comment by korikuzma** [comment]
@jarbesfeld says this output from #352 is correct

```json
{
  "gene": "NTRK1",
  "genomic_ac": "NC_000001.11",
  "tx_ac": "NM_002529.4",
  "seg_start": {
    "exon_ord": 0,
    "offset": 0,
    "genomic_location": {
      "type": "SequenceLocation",
      "sequenceReference": {
        "type": "SequenceReference",
        "refgetAccession": "SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO"
      },
      "start": 156860864
    }
  }
}
```
