### ISSUE TITLE
Expect gene symbol to be formatted correctly

### ISSUE THREAD

**Issue by jarbesfeld** [GenomicMedLab/cool-seq-tool#374]
There are a couple instances in the `tx_to_genomic` and `genomic_to_tx` methods where the gene symbol is converted to uppercase. We should edit to not convert the gene symbol to uppercase, as this should still be lower case for genes such as `C1orf216`

**Comment by jarbesfeld** [comment]
We should only be doing this if the gene does not match `r"^C\d+orf\d+$"`

**Comment by jsstevenson** [comment]
> We should only be doing this if the gene does not match r"^C\d+orf\d+$"

FWIW the tricky part is there are some CxORFy gene names that have extra words at the beginning or end

**Comment by korikuzma** [comment]
@jarbesfeld we can remove `upper` in the mapper class methods and just use what is listed in UTA.
